name: Test & Publish to Cloudflare
author: carlosdevpereira
description: Generates a test coverage report, uploads it to Cloudflare and comments results on available pull requests.
branding:
  color: white
  icon: check-circle

runs:
  using: "node16"
  main: "index.js"

inputs:
  framework:
    description: "The test framework to run the unit tests of the repository. (Only 'jest' is available for now.)"
    required: false
    default: "jest"
  githubToken:
    description: "The github token that will be used to comment the results on available pull requests."
    required: true
  cloudflareProjectName:
    description: "The name of the project on Cloudflare that will receive the coverage report."
    required: true
  cloudflareApiToken:
    description: "The API Token that will be used to upload the coverage report to Cloudflare."
    required: true
  cloudflareAccountId:
    description: "The Account ID that will be used to upload the coverage report to Cloudflare."
    required: true
  baseCloudflareDeploymentUrl:
    description: "The base URL configured on the target Cloudflare project from which the deployments will be served - It can also be a custom domain configured on the target project. (defaults to https://${cloudflareProjectName}.pages.dev)"
    required: false

outputs:
  coverage:
    description: "The final coverage percentage - average between the coverage values for Statements/Branches/Functions and Lines."
  reportUrl:
    description: "The final URL to the coverage report served by Cloudflare."
  affectedPullRequestUrls:
    description: "Pull request URL's that this action wrote comments on."
